In [44]:
# importing the moduels
import hvplot.pandas
import pandas as pd
import requests
import numpy as np
from scipy.stats import linregress
import matplotlib.pyplot as plt

In [45]:
# creating crime data frame
crime_df = pd.read_csv("Resources/Crime_Data_from_2020_to_present.csv")
crime_df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277

In [46]:
crime_df.count()

DR_NO             966951
Date Rptd         966951
DATE OCC          966951
TIME OCC          966951
AREA              966951
AREA NAME         966951
Rpt Dist No       966951
Part 1-2          966951
Crm Cd            966951
Crm Cd Desc       966951
Mocodes           826575
Vict Age          966951
Vict Sex          833245
Vict Descent      833235
Premis Cd         966937
Premis Desc       966375
Weapon Used Cd    325476
Weapon Desc       325476
Status            966950
Status Desc       966951
Crm Cd 1          966940
Crm Cd 2           68656
Crm Cd 3            2302
Crm Cd 4              64
LOCATION          966951
Cross Street      150218
LAT               966951
LON               966951
dtype: int64

In [47]:
crime_df.fillna(0, inplace= True)

In [48]:
crime_df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,0.0,0.0,1900 S LONGWOOD AV,0,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,0.0,0.0,1000 S FLOWER ST,0,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,0.0,0.0,0.0,1400 W 37TH ST,0,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,0.0,0.0,0.0,14000 RIVERSIDE DR,0,34.1576,-118.4387
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,0.0,0.0,0.0,1900 TRANSIENT,0,34.0944,-118.3277

In [49]:
# cleaning the date reported and the date occured column to remove the 12:00:00
crime_df["Date Rptd"] = crime_df["Date Rptd"].str.split().str[0]
crime_df["DATE OCC"] = crime_df["DATE OCC"].str.split().str[0]
crime_df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020,03/01/2020,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,0.0,0.0,1900 S LONGWOOD AV,0,34.0375,-118.3506
1,200106753,02/09/2020,02/08/2020,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,0.0,0.0,1000 S FLOWER ST,0,34.0444,-118.2628
2,200320258,11/11/2020,11/04/2020,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,0.0,0.0,0.0,1400 W 37TH ST,0,34.0210,-118.3002
3,200907217,05/10/2023,03/10/2020,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,0.0,0.0,0.0,14000 RIVERSIDE DR,0,34.1576,-118.4387
4,220614831,08/18/2022,08/17/2020,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,0.0,0.0,0.0,1900 TRANSIENT,0,34.0944,-118.3277

In [50]:
# cleaning the data to make the TIME OCC column read as 00:00 time structure
crime_df["TIME OCC"] = crime_df["TIME OCC"].astype(str).str.zfill(4).str[:2] + ":" + crime_df["TIME OCC"].astype(str).str.zfill(4).str[2:]
crime_df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020,03/01/2020,21:30,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,0.0,0.0,1900 S LONGWOOD AV,0,34.0375,-118.3506
1,200106753,02/09/2020,02/08/2020,18:00,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,0.0,0.0,1000 S FLOWER ST,0,34.0444,-118.2628
2,200320258,11/11/2020,11/04/2020,17:00,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,0.0,0.0,0.0,1400 W 37TH ST,0,34.0210,-118.3002
3,200907217,05/10/2023,03/10/2020,20:37,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,0.0,0.0,0.0,14000 RIVERSIDE DR,0,34.1576,-118.4387
4,220614831,08/18/2022,08/17/2020,12:00,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,0.0,0.0,0.0,1900 TRANSIENT,0,34.0944,-118.3277

In [51]:
# creating a data frame with just selected information 
selected_columns = ["DR_NO", "Date Rptd", "DATE OCC", "TIME OCC", "AREA", "AREA NAME", "Rpt Dist No", "Crm Cd", "Crm Cd Desc", "Status Desc" ,"Crm Cd 1", "Crm Cd 2", "LAT", "LON"]
date_time_df = crime_df[selected_columns]
date_time_df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd,Crm Cd Desc,Status Desc,Crm Cd 1,Crm Cd 2,LAT,LON
0,190326475,03/01/2020,03/01/2020,21:30,7,Wilshire,784,510,VEHICLE - STOLEN,Adult Arrest,510.0,998.0,34.0375,-118.3506
1,200106753,02/09/2020,02/08/2020,18:00,1,Central,182,330,BURGLARY FROM VEHICLE,Invest Cont,330.0,998.0,34.0444,-118.2628
2,200320258,11/11/2020,11/04/2020,17:00,3,Southwest,356,480,BIKE - STOLEN,Invest Cont,480.0,0.0,34.0210,-118.3002
3,200907217,05/10/2023,03/10/2020,20:37,9,Van Nuys,964,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),Invest Cont,343.0,0.0,34.1576,-118.4387
4,220614831,08/18/2022,08/17/2020,12:00,6,Hollywood,666,354,THEFT OF IDENTITY,Invest Cont,354.0,0.0,34.0944,-118.3277

In [52]:
# renaming the selceted columns to be more readable
date_time_df.columns = date_time_df.columns.str.title()
date_time_df

,Dr_No,Date Rptd,Date Occ,Time Occ,Area,Area Name,Rpt Dist No,Crm Cd,Crm Cd Desc,Status Desc,Crm Cd 1,Crm Cd 2,Lat,Lon
0,190326475,03/01/2020,03/01/2020,21:30,7,Wilshire,784,510,VEHICLE - STOLEN,Adult Arrest,510.0,998.0,34.0375,-118.3506
1,200106753,02/09/2020,02/08/2020,18:00,1,Central,182,330,BURGLARY FROM VEHICLE,Invest Cont,330.0,998.0,34.0444,-118.2628
2,200320258,11/11/2020,11/04/2020,17:00,3,Southwest,356,480,BIKE - STOLEN,Invest Cont,480.0,0.0,34.0210,-118.3002
3,200907217,05/10/2023,03/10/2020,20:37,9,Van Nuys,964,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),Invest Cont,343.0,0.0,34.1576,-118.4387
4,220614831,08/18/2022,08/17/2020,12:00,6,Hollywood,666,354,THEFT OF IDENTITY,Invest Cont,354.0,0.0,34.0944,-118.3277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966946,242004546,01/16/2024,01/16/2024,15:10,20,Olympic,2013,624,BATTERY - SIMPLE ASSAULT,Invest Cont,624.0,0.0,34.0690,-118.3054
966947,240710284,07/24/2024,07/23/2024,14:00,7,Wilshire,788,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0362,-118.3284
966948,240104953,01/15/2024,01/15/2024,01:00,1,Central,101,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),Invest Cont,745.0,0.0,34.0685,-118.2460
966949,241711348,07/19/2024,07/19/2024,07:57,17,Devonshire,1751,888,TRESPASSING,Invest Cont,888.0,0.0,34.2500,-118.5990
966950,240309674,04/24/2024,04/24/2024,15:00,3,Southwest,358,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",Invest Cont,230.0,0.0,34.0215,-118.2868

In [60]:
# getting the value counts for the type of crime committed
desc = date_time_df["Crm Cd"].value_counts()
print(desc)
desc_2 = date_time_df["Date Occ"].value_counts()
print(desc_2)

Crm Cd
510    107349
624     74623
330     60128
354     59801
740     58702
        ...
475         6
904         5
445         4
906         4
926         1
Name: count, Length: 139, dtype: int64
Date Occ
01/01/2020    1151
01/01/2023    1139
12/02/2022    1132
02/01/2023    1092
10/01/2022    1078
              ...
07/09/2024     200
08/02/2024     193
08/03/2024     168
08/04/2024     134
08/05/2024      41
Name: count, Length: 1679, dtype: int64

In [65]:
# looking at a specific value of the Date Occ column 
date_time_df.loc[date_time_df["Crm Cd"]== 510].head(60)

,Dr_No,Date Rptd,Date Occ,Time Occ,Area,Area Name,Rpt Dist No,Crm Cd,Crm Cd Desc,Status Desc,Crm Cd 1,Crm Cd 2,Lat,Lon
0,190326475,03/01/2020,03/01/2020,21:30,7,Wilshire,784,510,VEHICLE - STOLEN,Adult Arrest,510.0,998.0,34.0375,-118.3506
13,221008844,05/06/2022,11/01/2020,01:30,10,West Valley,1029,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1939,-118.4859
24,200412582,09/09/2020,09/09/2020,06:30,4,Hollenbeck,413,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0820,-118.2130
78,201810154,04/26/2020,04/22/2020,19:00,18,Southeast,1802,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9547,-118.2717
92,231510293,05/27/2023,11/24/2020,02:00,15,N Hollywood,1504,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.2071,-118.3965
106,201410122,04/28/2020,04/28/2020,01:00,14,Pacific,1406,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0238,-118.4095
167,201308739,03/27/2020,03/27/2020,12:10,13,Newton,1333,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0170,-118.2643
170,221007765,04/10/2022,04/06/2020,12:00,10,West Valley,1024,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1958,-118.5399
198,201112065,07/31/2020,07/30/2020,20:30,11,Northeast,1161,510,VEHICLE - STOLEN,Adult Arrest,510.0,0.0,34.0953,-118.2974
240,220509193,05/17/2022,10/01/2020,12:00,5,Harbor,528,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.7910,-118.2469
248,221225797,12/22/2022,12/22/2020,02:20,12,77th Street,1249,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9774,-118.2827
313,230506149,02/28/2023,07/01/2020,12:00,5,Harbor,521,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.7694,-118.2955
365,201215394,06/26/2020,06/25/2020,22:00,12,77th Street,1259,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9747,-118.2587
373,211409233,04/06/2021,08/19/2020,17:30,14,Pacific,1496,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9456,-118.3932
388,201312835,06/25/2020,06/23/2020,21:00,13,Newton,1342,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0145,-118.2658
411,202112289,08/03/2020,07/30/2020,14:00,21,Topanga,2113,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.2083,-118.6190
414,220305685,02/08/2022,02/02/2020,20:00,3,Southwest,392,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0037,-118.3294
448,230209650,04/26/2023,01/08/2020,14:00,2,Rampart,265,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0544,-118.2767
490,221513146,08/06/2022,04/20/2020,12:00,15,N Hollywood,1503,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.2010,-118.3990
498,200114396,07/06/2020,07/04/2020,01:00,1,Central,157,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0423,-118.2453
514,231317622,09/20/2023,09/11/2020,11:00,13,Newton,1377,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9930,-118.2446
529,200912561,07/20/2020,07/20/2020,07:00,9,Van Nuys,937,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1812,-118.4356
537,211504819,01/22/2021,07/10/2020,12:00,15,N Hollywood,1547,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1681,-118.3790
564,220414491,10/20/2022,10/19/2020,20:00,4,Hollenbeck,442,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0577,-118.2134
566,200207955,03/19/2020,03/19/2020,01:30,2,Rampart,236,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0632,-118.2693
595,221506014,02/20/2022,02/17/2020,22:00,15,N Hollywood,1526,510,VEHICLE - STOLEN,Adult Arrest,510.0,0.0,34.1812,-118.3817
614,210709140,05/28/2021,05/28/2020,00:45,7,Wilshire,743,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0575,-118.3599
622,222007966,04/02/2022,04/02/2020,00:10,20,Olympic,2036,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0598,-118.2954
642,200905707,02/08/2020,02/07/2020,20:00,9,Van Nuys,939,510,VEHICLE - STOLEN,Adult Other,510.0,0.0,34.1803,-118.4204
672,220506283,03/01/2022,01/01/2020,12:00,5,Harbor,506,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.8280,-118.3038
675,220406802,03/25/2022,03/24/2020,02:45,4,Hollenbeck,411,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0768,-118.2228
703,201813532,07/05/2020,07/05/2020,14:00,18,Southeast,1842,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9374,-118.2784
807,201511143,06/11/2020,06/09/2020,21:30,15,N Hollywood,1517,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1940,-118.3768
820,202011756,07/05/2020,07/05/2020,04:30,20,Olympic,2071,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0454,-118.3134
826,221208508,03/22/2022,10/15/2020,12:00,12,77th Street,1268,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9640,-118.2739
830,221222292,10/25/2022,10/25/2020,02:00,12,77th Street,1283,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9527,-118.3058
856,220810198,05/31/2022,07/01/2020,16:00,8,West LA,889,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0414,-118.3825
869,201909255,04/29/2020,04/28/2020,17:00,19,Mission,1952,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.2537,-118.4698
887,221316918,09/01/2022,09/01/2020,06:00,13,Newton,1317,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0284,-118.2400
903,200308100,03/07/2020,03/06/2020,22:00,3,Southwest,317,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0344,-118.2915
913,221614385,11/19/2022,11/18/2020,21:30,16,Foothill,1684,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.2103,-118.3943
944,221214939,07/01/2022,07/20/2020,19:00,12,77th Street,1266,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9661,-118.2849
984,201410297,05/01/2020,04/30/2020,19:00,14,Pacific,1438,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0172,-118.4148
1045,231407629,03/29/2023,11/05/2020,18:00,14,Pacific,1437,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0166,-118.4201
1066,202107032,03/07/2020,03/06/2020,19:00,21,Topanga,2105,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.2198,-118.5975
1092,232014224,08/17/2023,08/05/2020,12:00,20,Olympic,2021,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0653,-118.3183
1193,231013398,09/06/2023,12/15/2020,17:00,10,West Valley,1075,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1663,-118.5298
1230,201316139,08/28/2020,08/28/2020,11:00,13,Newton,1307,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0392,-118.2455
1257,200517540,12/07/2020,11/30/2020,22:55,5,Harbor,541,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.7553,-118.3056
1300,221613551,10/23/2022,10/22/2020,23:30,16,Foothill,1642,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.2546,-118.4179
1313,230505482,02/09/2023,06/01/2020,14:00,5,Harbor,519,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.7930,-118.2428
1353,200510354,06/08/2020,06/08/2020,03:30,5,Harbor,587,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.7179,-118.2898
1366,211004109,01/04/2021,12/31/2020,15:00,10,West Valley,1008,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1939,-118.4924
1372,202018542,12/18/2020,12/16/2020,23:00,20,Olympic,2058,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0524,-118.2904
1401,200410136,06/24/2020,06/24/2020,07:00,4,Hollenbeck,413,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0809,-118.2132
1404,200814461,09/24/2020,09/24/2020,17:10,8,West LA,898,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0375,-118.3886
1464,220406238,03/10/2022,03/09/2020,20:00,4,Hollenbeck,449,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.0520,-118.1958
1478,230815276,10/05/2023,10/05/2020,10:00,8,West LA,807,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,34.1126,-118.4441
1496,201215562,06/29/2020,06/29/2020,07:30,12,77th Street,1263,510,VEHICLE - STOLEN,Invest Cont,510.0,0.0,33.9655,-118.3046
1532,221015776,10/28/2022,03/28/2020,12:00,10,West Valley,1035,510,VEHICLE - STOLEN,Invest Cont,341.0,510.0,34.1885,-118.5197